
name: ranger-http-server
initialRotationStatus: false

rangerConfiguration:
  namespace: test
  httpClientConfigs:
    - host: localhost
      port: 8080

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 7080
  adminConnectors:
    - type: http
      port: 7081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO

  loggers:
    com.flipkart.ranger.http.server: DEBUG

  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"


